version: "3"
services:
  ubuntu:
    build: 
      context: ./containers/ssh
      dockerfile: ./Dockerfile
    volumes:
      - ubuntu-volume:/var/app
    ports:
      - 10022:10022
volumes:
  ubuntu-volume:

